language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - jruby-9.1.7.0
  - jruby-9.1.16.0
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

jdk:
  - openjdk8

before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rvm all-gemsets do gem uninstall bundler -ax || true
  - gem install bundler -v "< 2"